//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaixaCEO
{
    using System;
    using System.Collections.Generic;
    
    public partial class cargos
    {
        public cargos()
        {
            this.membros = new HashSet<membros>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
    
        public virtual ICollection<membros> membros { get; set; }
    }
}
