//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaixaCEO
{
    using System;
    using System.Collections.Generic;
    
    public partial class doacoes
    {
        public int id { get; set; }
        public System.DateTime dia { get; set; }
        public string nome_doador { get; set; }
        public decimal valor { get; set; }
        public string destinacao { get; set; }
        public int id_forma_oferta { get; set; }
        public int id_lancamento { get; set; }
    
        public virtual forma_oferta forma_oferta { get; set; }
        public virtual lancamentos lancamentos { get; set; }
    }
}
