//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaixaCEO
{
    using System;
    using System.Collections.Generic;
    
    public partial class entradas
    {
        public int id { get; set; }
        public int id_lancamento { get; set; }
        public string tabela_origem { get; set; }
        public decimal valor { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime competencia { get; set; }
    
        public virtual lancamentos lancamentos { get; set; }
    }
}
