//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaixaCEO
{
    using System;
    using System.Collections.Generic;
    
    public partial class lancamentos
    {
        public lancamentos()
        {
            this.dizimos = new HashSet<dizimos>();
            this.doacoes = new HashSet<doacoes>();
            this.entradas = new HashSet<entradas>();
            this.primicias = new HashSet<primicias>();
            this.saidas = new HashSet<saidas>();
        }
    
        public int id { get; set; }
        public string tipo { get; set; }
        public int codigo { get; set; }
        public string nome { get; set; }
        public byte[] descricao { get; set; }
        public string tabela_origem { get; set; }
        public int id_tabela_origem { get; set; }
        public decimal valor { get; set; }
        public System.DateTime data { get; set; }
    
        public virtual ICollection<dizimos> dizimos { get; set; }
        public virtual ICollection<doacoes> doacoes { get; set; }
        public virtual ICollection<entradas> entradas { get; set; }
        public virtual ICollection<primicias> primicias { get; set; }
        public virtual ICollection<saidas> saidas { get; set; }
    }
}
