//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaixaCEO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppDB : DbContext
    {
        public AppDB()
            : base("name=AppDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<usuarios> usuarios { get; set; }
        public DbSet<cargos> cargos { get; set; }
        public DbSet<dizimos> dizimos { get; set; }
        public DbSet<doacoes> doacoes { get; set; }
        public DbSet<entradas> entradas { get; set; }
        public DbSet<forma_oferta> forma_oferta { get; set; }
        public DbSet<lancamentos> lancamentos { get; set; }
        public DbSet<membros> membros { get; set; }
        public DbSet<ofertas> ofertas { get; set; }
        public DbSet<primicias> primicias { get; set; }
        public DbSet<saidas> saidas { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tipo_culto> tipo_culto { get; set; }
    }
}
