//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaixaCEO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ofertas
    {
        public int id { get; set; }
        public System.DateTime dia { get; set; }
        public int qtd_adultos { get; set; }
        public int qtd_criancas { get; set; }
        public decimal total_oferta { get; set; }
        public bool missao { get; set; }
        public int id_tipo_culto { get; set; }
        public int id_membro_ministrante { get; set; }
        public int id_forma_oferta { get; set; }
    
        public virtual forma_oferta forma_oferta { get; set; }
        public virtual membros membros { get; set; }
        public virtual tipo_culto tipo_culto { get; set; }
    }
}
