//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaixaCEO
{
    using System;
    using System.Collections.Generic;
    
    public partial class primicias
    {
        public int id { get; set; }
        public System.DateTime data { get; set; }
        public System.DateTime periodo { get; set; }
        public decimal valor { get; set; }
        public int id_membro { get; set; }
        public int id_forma_oferta { get; set; }
        public int id_lancamento { get; set; }
    
        public virtual forma_oferta forma_oferta { get; set; }
        public virtual lancamentos lancamentos { get; set; }
        public virtual membros membros { get; set; }
    }
}
